# This is the Supabase configuration file

project_id = "tlqdmgudwsfavjslpplh"

[auth]
site_url = "https://test.dopz.work"
additional_redirect_urls = ["https://test.dopz.work/*", "http://localhost:5173/*"]
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true

[auth.external.github]
enabled = false

[auth.external.google]
enabled = false

[auth.external.azure]
enabled = false

[storage]
file_size_limit = "50MiB"

[api]
enabled_apis = ["rest", "graphql", "realtime"]

[api.cors]
enabled = true
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
exposed_headers = ["Content-Range", "Range"]
max_age = 3600