# A string used to distinguish different Supabase projects on the same host.
project_id = "tlqdmgudwsfavjslpplh"

[auth]
# The base URL of your website.
site_url = "https://test.dopz.work"
# A list of URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://test.dopz.work/*", "http://localhost:5173/*"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour).
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = false
# If enabled, a user will be required to confirm any email change.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = true

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"