[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  command = "npm run build"
  [context.production.environment]
    VITE_APP_ENV = "production"

# Test branch context
[context.test]
  command = "npm run build"
  [context.test.environment]
    VITE_APP_ENV = "test"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Deploy preview context
[context.deploy-preview]
  command = "npm run build"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://tlqdmgudwsfavjslpplh.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://tlqdmgudwsfavjslpplh.supabase.co;"